import { getAgentBootstrapContract } from '../lib/agent/bootstrap'

function lines(parts: Array<string | null | undefined | false>): string {
  return parts.filter(Boolean).join('\n')
}

function withBaseUrl(baseUrl: string, routePath: string): string {
  return `${baseUrl.replace(/\/$/, '')}${routePath}`
}

export function renderAgentsMarkdown(authenticated: boolean, baseUrl = 'http://localhost:3000'): string {
  const bootstrap = getAgentBootstrapContract()

  const header = lines([
    '# /agents.md',
    '',
    'Agent contract for this Nabu instance.',
    '',
    'This surface is for agents. It returns raw markdown, not HTML.',
    '',
    '## Agent operating mode',
    '',
    '- Read this route before touching the browser UI.',
    '- Authenticate over HTTP, persist the session cookie, write via API, then verify by path.',
    '- Do not use browser automation or browser-use for normal note operations.',
    '- Use the browser UI only for human navigation or explicit UI testing.',
    '',
    '## Authentication',
    '',
    `- ${bootstrap.auth.method} ${bootstrap.auth.endpoint}`,
    `- Content-Type: ${bootstrap.auth.contentType}`,
    `- Fields: ${bootstrap.auth.fields.join(', ')}`,
    `- Session cookie: ${bootstrap.auth.cookieName}`,
    '- Persist the session cookie and reuse it on subsequent requests.',
    '- Existing password/session agents remain supported; shared collaborators use `Authorization: Bearer <scoped-access-token>`.',
    '- Use a normal HTTP client like `curl` for writes.',
    '',
    '## Identity',
    '',
    `- Canonical note identity: ${bootstrap.identity.canonical}`,
    `- Deterministic read: ${bootstrap.identity.deterministicRead}<path>`,
    `- Convenience read: ${bootstrap.identity.convenienceRead}`,
    `- ${bootstrap.identity.note}`,
    '',
    '## MCP',
    '',
    `- Local command: \`${bootstrap.mcp.localCommand}\``,
    `- Direct-vault environment: ${bootstrap.mcp.directEnvironment.join(', ')}`,
    `- Deployed-service environment: ${bootstrap.mcp.remoteEnvironment.join(', ')}`,
    `- Transport: ${bootstrap.mcp.transport}`,
    `- Native remote MCP endpoint: ${bootstrap.mcp.nativeRemoteEndpoint}`,
    '- Keep the agent token outside the repository and use HTTPS for non-loopback services.',
    '',
  ])

  const pitfalls = lines([
    '## Common agent pitfalls',
    '',
    '- Use `rawMarkdown`, not top-level `body` or `content`.',
    '- Use vault-relative paths only.',
    '- Use deterministic by-path reads after every mutation.',
    '- When writing notes, prefer canonical frontmatter metadata (`title`, `summary`, `tags`, `authors`, `source`, `references`).',
    '- Rename does not rewrite wiki-links or markdown links yet.',
    '- Folder delete is empty-only and non-recursive.',
    '- Shared spaces are temporary, live recursive knowledge boundaries; all descendants created under the shared root remain accessible until expiry or revocation.',
    '',
  ])

  if (!authenticated) {
    return lines([
      header,
      pitfalls,
      'Authenticate first, then read this route again for the full write contract.',
      '',
      'Full authenticated contract includes note create/update/move/delete and empty-folder delete.',
      '',
      'Example login:',
      '```bash',
      "curl -i -c /tmp/nabu-cookies.txt \\",
      "  -H 'Content-Type: application/x-www-form-urlencoded' \\",
      "  --data 'password=YOUR_PASSWORD&redirect=%2Fagents.md' \\",
      `  ${withBaseUrl(baseUrl, '/api/auth/login')}`,
      '```',
      '',
    ])
  }

  return lines([
    header,
    '## Read surfaces',
    '',
    '- GET /api/vault/',
    '- GET /api/vault/index/stats',
    '- GET /api/vault/tree',
    '- GET /api/vault/folders?path=',
    '- GET /api/vault/notes/$slug',
    '- GET /api/vault/notes/by-path?path=',
    '- GET /api/vault/notes/neighborhood?path=',
    '- GET /api/vault/search?q=&path=&tag=&limit=&offset=',
    '',
    '## Write surfaces',
    '',
    '- POST /api/vault/folders',
    '- DELETE /api/vault/folders?path=',
    '- POST /api/vault/notes',
    '- PUT /api/vault/notes/by-path',
    '- PATCH /api/vault/notes/by-path',
    '- DELETE /api/vault/notes/by-path?path=',
    '',
    '## Shared spaces',
    '',
    '- POST /api/shared-spaces/proposals — preview a complete recursive scope; this does not share anything.',
    '- POST /api/shared-spaces/ — explicitly confirm a proposal and create a one-time invite.',
    '- GET /api/shared-spaces/ — list owned leases.',
    '- GET /api/shared-spaces/:sharedSpaceId — inspect an owned lease.',
    '- POST /api/shared-spaces/:sharedSpaceId/revoke — revoke access immediately.',
    '- POST /api/shared-spaces/:sharedSpaceId/invites — create another one-time invite.',
    '- POST /api/shared-spaces/:sharedSpaceId/extend — explicitly extend within the 30-day maximum.',
    '- POST /api/shared-spaces/invites/redeem — redeem an invite once and receive a scoped bearer token.',
    '- Invite URLs are valid for one hour and never contain a long-lived access token.',
    '- Shared-space leases default to 7 days, allow 1–30 days, and are live recursive path boundaries.',
    '',
    '### Shared-space workflow',
    '',
    '1. Propose the folder and show the returned files, folders, counts, size, and live-scope warning to the human.',
    '2. Ask for explicit confirmation; do not infer it from the proposal request.',
    '3. Confirm with `{ "proposalId": "...", "confirmed": true, "durationDays": 14, "permissions": ["read", "write"] }`.',
    '4. Give the one-time invite URL to the collaborator. The collaborator redeems it and uses the returned access token as a bearer token on normal vault APIs.',
    '',
    '## Revision-aware writes',
    '',
    '- Every note read returns `note.revision` and `ETag: "<revision>"`.',
    '- New shared-token writes must send `If-Match: "<revision>"` or `expectedRevision` in the update/move body.',
    '- During migration, legacy owner writes without a revision still succeed and return `migration.code = WRITE_REVISION_MIGRATION_REQUIRED`.',
    '- `428 WRITE_REVISION_REQUIRED`: GET the supplied `readUrl`, merge your intended change, then retry with its revision.',
    '- `409 STALE_NOTE_REVISION`: GET `readUrl`, merge against `currentRevision`, then retry. Never silently overwrite a newer note.',
    '',
    '## Write semantics',
    '',
    '- Note create/update bodies must use `rawMarkdown` or a structured `document` payload, but never both.',
    '- Structured document payloads are preferred for agent-authored notes because they render canonical frontmatter metadata.',
    '- By-path note reads include the exact `rawMarkdown` and additive `rawContentHash` fields used by the human source editor.',
    '- Human source saves may send `expectedRawContentHash`; a `409` means the raw file changed since it was read. Existing `expectedContentHash` remains the parsed-note agent contract.',
    '- Note move body: `{ "path": "from.md", "toPath": "to.md" }`.',
    '- Note delete deletes a single note only.',
    '- Folder delete only deletes empty folders.',
    '- Successful mutations rebuild the in-memory index immediately.',
    '',
    '## Error semantics',
    '',
    '- `400` invalid path or invalid request body',
    '- `401` missing or expired authenticated session',
    '- `404` note or folder not found',
    '- `409` create conflict, move destination exists, or folder is not empty',
    '- `409 STALE_NOTE_REVISION` means re-read, merge, and retry with the latest revision',
    '- `428 WRITE_REVISION_REQUIRED` means the request must include `If-Match` or `expectedRevision`',
    '',
    pitfalls,
    '## Copy-paste examples',
    '',
    '### Login with cookie jar',
    '```bash',
    "curl -i -c /tmp/nabu-cookies.txt \\",
    "  -H 'Content-Type: application/x-www-form-urlencoded' \\",
    "  --data 'password=YOUR_PASSWORD&redirect=%2Fagents.md' \\",
    `  ${withBaseUrl(baseUrl, '/api/auth/login')}`,
    '```',
    '',
    '### Create note',
    '```bash',
    "curl -s -b /tmp/nabu-cookies.txt \\",
    `  -X POST ${withBaseUrl(baseUrl, '/api/vault/notes')} \\`,
    "  -H 'Content-Type: application/json' \\",
    "  --data '{\"path\":\"projects/docsyde/sales/icp-findings\",\"rawMarkdown\":\"# ICP Findings\"}'",
    '```',
    '',
    '### Update note',
    '```bash',
    "curl -s -b /tmp/nabu-cookies.txt \\",
    `  -X PUT ${withBaseUrl(baseUrl, '/api/vault/notes/by-path')} \\`,
    "  -H 'Content-Type: application/json' \\",
    "  --data '{\"path\":\"projects/docsyde/sales/icp-findings.md\",\"rawMarkdown\":\"# ICP Findings\\n\\nUpdated\"}'",
    '```',
    '',
    '### Move note',
    '```bash',
    "curl -s -b /tmp/nabu-cookies.txt \\",
    `  -X PATCH ${withBaseUrl(baseUrl, '/api/vault/notes/by-path')} \\`,
    "  -H 'Content-Type: application/json' \\",
    "  --data '{\"path\":\"docsyde/sales/icp-findings.md\",\"toPath\":\"projects/docsyde/sales/icp-findings.md\"}'",
    '```',
    '',
    '### Delete note',
    '```bash',
    "curl -s -b /tmp/nabu-cookies.txt \\",
    `  -X DELETE '${withBaseUrl(baseUrl, '/api/vault/notes/by-path?path=projects/docsyde/sales/icp-findings.md')}'`,
    '```',
    '',
    '### Delete empty folder',
    '```bash',
    "curl -s -b /tmp/nabu-cookies.txt \\",
    `  -X DELETE '${withBaseUrl(baseUrl, '/api/vault/folders?path=docsyde/sales')}'`,
    '```',
    '',
    '### Verify note by path',
    '```bash',
    "curl -s -b /tmp/nabu-cookies.txt \\",
    `  '${withBaseUrl(baseUrl, '/api/vault/notes/by-path?path=projects/docsyde/sales/icp-findings.md')}'`,
    '```',
    '',
  ])
}
