import { getAgentBootstrapContract } from '../lib/agent/bootstrap'
import { SHARED_SPACE_AGENT_CONTRACT } from '../lib/shared-spaces/agent-contract'

function lines(parts: Array<string | null | undefined | false>): string {
  return parts.filter(Boolean).join('\n')
}

function withBaseUrl(baseUrl: string, routePath: string): string {
  return `${baseUrl.replace(/\/$/, '')}${routePath}`
}

export function renderAgentsMarkdown(baseUrl = 'http://localhost:3000'): string {
  const bootstrap = getAgentBootstrapContract()
  const loginUrl = withBaseUrl(baseUrl, '/api/auth/login')
  const proposalUrl = withBaseUrl(baseUrl, '/api/shared-spaces/proposals')
  const sharedSpacesUrl = withBaseUrl(baseUrl, '/api/shared-spaces/')
  const redeemUrl = withBaseUrl(baseUrl, '/api/shared-spaces/invites/redeem')
  const readLinkUrl = withBaseUrl(baseUrl, '/api/shared-spaces/:sharedSpaceId/read-link')
  const notesUrl = withBaseUrl(baseUrl, '/api/vault/notes')
  const notesByPathUrl = withBaseUrl(baseUrl, '/api/vault/notes/by-path')

  return lines([
    '# /agents.md',
    '',
    'Complete agent contract for this Nabu instance.',
    '',
    'This document is public and returns raw Markdown. Read this route before touching the browser UI. Protected API operations still require owner authentication or a scoped shared-space token.',
    '',
    '## Operating rules',
    '',
    '- Use the HTTP API for normal note operations. Use MCP when the deployment or agent integration requires it.',
    '- Do not use browser automation or browser-use for normal note operations. Use the browser only for human navigation or explicit UI testing.',
    '- Use HTTPS for non-loopback deployments.',
    '- Check the HTTP status and JSON body on every request; do not treat an HTTP error as a successful operation.',
    '- Never log, persist, or commit passwords, session cookies, invite URLs, access tokens, or bearer credentials.',
    '- Use vault-relative paths only. Never send absolute paths, traversal paths, or paths outside the vault.',
    '',
    '## Base URL and contract discovery',
    '',
    '- Set `NABU_URL` to this deployment base URL, without a trailing slash.',
    `- This deployment base URL is ${baseUrl.replace(/\/$/, '')}.`,
    '- Fetch `${NABU_URL}/agents.md` again whenever the deployment or API version is uncertain.',
    '- The contract is available without authentication so a new agent can discover the correct workflow before logging in or redeeming an invite.',
    '',
    '## Authentication',
    '',
    '- Owner login and remote MCP use the same Nabu password; remote MCP derives its owner bearer credential internally.',
    '- Owner login uses `POST /api/auth/login` with `Content-Type: application/x-www-form-urlencoded` and fields `password` and `redirect`.',
    `- A successful login sets the ${bootstrap.auth.cookieName} session cookie. Persist it in a cookie jar and reuse it for owner requests.`,
    '- Shared collaborators use `Authorization: Bearer <scoped-access-token>`; they do not use the owner password.',
    '- A shared token is scoped to exactly one shared space, its permissions, and its lease expiry. It cannot be broadened or extended by the collaborator.',
    '- A read-only URL token is a separate browser/API capability. It has read permission only and never grants owner authentication or write access.',
    '',
    '### Owner login example',
    '',
    '```bash',
    "curl -i -c /tmp/nabu-cookies.txt \\",
    "  -H 'Content-Type: application/x-www-form-urlencoded' \\",
    "  --data 'password=YOUR_PASSWORD&redirect=%2Fagents.md' \\",
    `  ${loginUrl}`,
    '```',
    '',
    '## Note identity and read surfaces',
    '',
    `- Canonical note identity is ${bootstrap.identity.canonical} (the vault-relative relPath).`,
    `- Prefer deterministic reads through ${bootstrap.identity.deterministicRead}<path>.`,
    `- Slug lookup through ${bootstrap.identity.convenienceRead} is convenience-only and may collide.`,
    '- URL-encode query parameters such as `path`, `q`, and `tag`.',
    '',
    '- `GET /api/vault/`',
    '- `GET /api/vault/index/stats`',
    '- `GET /api/vault/tree`',
    '- `GET /api/vault/folders?path=`',
    '- `GET /api/vault/notes/$slug`',
    '- `GET /api/vault/notes/by-path?path=`',
    '- `GET /api/vault/notes/neighborhood?path=`',
    '- `GET /api/vault/search?q=&path=&tag=&limit=&offset=`',
    '- `GET /api/vault/assets?path=` for in-scope local images and files',
    '',
    '## Note writes',
    '',
    '- `POST /api/vault/folders`',
    '- `DELETE /api/vault/folders?path=`',
    '- `POST /api/vault/notes`',
    '- `PUT /api/vault/notes/by-path`',
    '- `PATCH /api/vault/notes/by-path`',
    '- `DELETE /api/vault/notes/by-path?path=` (single note only)',
    '',
    '- Use `rawMarkdown`, not top-level `body` or `content`. Send note text as `rawMarkdown` or a structured `document`, never both.',
    '- Folder delete is empty-only and non-recursive.',
    '- When writing notes, prefer canonical frontmatter metadata through structured documents. Supported metadata includes `title`, `summary`, `tags`, `authors`, `source`, and `references`.',
    '- Use deterministic by-path reads after every mutation. Read the note again by canonical path and verify the content and metadata.',
    '- Move notes with `{ "path": "from.md", "toPath": "to.md" }`. Moves do not rewrite wiki-links or Markdown links.',
    '- Successful mutations rebuild the in-memory index immediately.',
    '',
    '### Revision-aware writes',
    '',
    '- Every note read returns `note.revision` and an `ETag` such as `"revision-42"`.',
    '- Shared-token updates and moves must send `If-Match: "<revision>"` or `expectedRevision` in the request body.',
    '- Existing owner agents may continue legacy writes without a revision during migration. Those responses include `migration.code = WRITE_REVISION_MIGRATION_REQUIRED`; migrate that agent to revision-aware writes.',
    '- On `428 WRITE_REVISION_REQUIRED`, GET the supplied `readUrl`, merge the intended change, and retry with the returned revision.',
    '- On `409 STALE_NOTE_REVISION`, GET `readUrl`, merge against `currentRevision`, and retry. Never silently overwrite a newer note.',
    '- Human source saves may send `expectedRawContentHash`; a `409` then means the raw file changed since it was read. `expectedContentHash` remains the parsed-note agent contract.',
    '',
    '### Create and update examples',
    '',
    '```bash',
    `curl -sS -b /tmp/nabu-cookies.txt -X POST ${notesUrl} \\`,
    "  -H 'Content-Type: application/json' \\",
    "  --data '{\"path\":\"projects/example/notes/example.md\",\"rawMarkdown\":\"# Example\"}'",
    '',
    `curl -sS -b /tmp/nabu-cookies.txt ${notesByPathUrl}?path=projects%2Fexample%2Fnotes%2Fexample.md`,
    '',
    `curl -sS -b /tmp/nabu-cookies.txt -X PUT ${notesByPathUrl} \\`,
    "  -H 'Content-Type: application/json' \\",
    "  -H 'If-Match: \"REVISION_FROM_READ\"' \\",
    "  --data '{\"path\":\"projects/example/notes/example.md\",\"rawMarkdown\":\"# Example\\n\\nUpdated\"}'",
    '```',
    '',
    '## Temporary shared spaces',
    '',
    'Shared spaces are temporary, live recursive knowledge boundaries. Existing descendants are accessible immediately, and files or folders created later under the shared root become accessible automatically until the lease expires or is revoked.',
    '',
    '- Do not share the vault root.',
    '- Shared roots are segment-aware: `little-helpers` does not include `little-helpers-private`.',
    '- Shared spaces have no exclusion rules in v1; choose a narrower root instead.',
    '- A shared token cannot access parent paths, siblings, symlink targets, or metadata that reveals private paths.',
    '- Private linked notes are filtered from search, backlinks, neighborhoods, and graph results.',
    '- Lease duration defaults to 7 days, has a minimum of 1 day, and has a maximum of 183 days.',
    '- Access expires synchronously using server time. Cleanup may happen asynchronously.',
    '- Invite URLs are opaque one-time capabilities valid for one hour. They are not long-lived access tokens.',
    '',
    '### Shared-space contract versions',
    '',
    `- New clients should feature-detect \`contractVersion: ${SHARED_SPACE_AGENT_CONTRACT.version}\` in proposal, confirmation, and redemption responses. The version-${SHARED_SPACE_AGENT_CONTRACT.version} contract is the portable profile and retry contract documented below.`,
    `- Requests without \`contractVersion: ${SHARED_SPACE_AGENT_CONTRACT.version}\`, and proposals persisted without a version marker, retain version-1 behavior. Version-1 confirmation is still explicit, and a version-1 invite remains one-shot when redeemed without \`${SHARED_SPACE_AGENT_CONTRACT.redemption.idempotencyHeader}\`.`,
    '- A version-2 proposal binds the normalized root path, requested duration, and permission set. Confirmation may repeat those fields for compatibility, but a mismatch is rejected; it never silently changes consent. Create a new proposal after a mismatch or expiry.',
    '',
    '### 1. Propose a scope (no sharing side effect)',
    '',
    `POST ${proposalUrl}`,
    '',
    '```json',
    '{',
    `  "contractVersion": ${SHARED_SPACE_AGENT_CONTRACT.version},`,
    '  "path": "projects/example/shared",',
    '  "durationDays": 14,',
    '  "permissions": ["read", "write"]',
    '}',
    '```',
    '',
    '- Normalize and validate the vault-relative path first.',
    '- Reject empty/root paths, absolute paths, traversal, symlinks, and paths outside the vault.',
    '- Show the human the complete recursive `files` and `folders` lists, `fileCount`, `totalBytes`, `warnings`, proposal ID, and expiry before asking for confirmation.',
    '- The preview must clearly state: `Any files or folders added under this path later will also be part of the shared space.`',
    '- Version 2 requires all four fields above. The server stores the normalized path, duration, and canonical permission order with the proposal.',
    '- A proposal alone never shares anything.',
    '',
    '### 2. Confirm explicitly and create an invite',
    '',
    `POST ${sharedSpacesUrl}`,
    '',
    '```json',
    '{',
    '  "proposalId": "proposal_123",',
    '  "confirmed": true,',
    `  "contractVersion": ${SHARED_SPACE_AGENT_CONTRACT.version},`,
    '  "path": "projects/example/shared",',
    '  "durationDays": 14,',
    '  "permissions": ["read", "write"]',
    '}',
    '```',
    '',
    '- `confirmed: true` is mandatory. Never infer confirmation from a proposal request or from the original user wording.',
    '- `durationDays` must be between 1 and 183. Omitted duration uses the 7-day default where supported.',
    '- The proposal must be unexpired and owned by the authenticated owner.',
    `- A version-${SHARED_SPACE_AGENT_CONTRACT.version} confirmation response preserves the one-time \`inviteUrl\`, \`inviteExpiresAt\`, and \`sharedSpaceExpiresAt\`, and includes a \`redemption\` descriptor with \`contractVersion: ${SHARED_SPACE_AGENT_CONTRACT.version}\`, relative \`endpoint: "${SHARED_SPACE_AGENT_CONTRACT.redemption.endpoint}"\`, \`method: "${SHARED_SPACE_AGENT_CONTRACT.redemption.method}"\`, exact \`bodyField: "${SHARED_SPACE_AGENT_CONTRACT.redemption.bodyField}"\`, \`idempotencyHeader: "${SHARED_SPACE_AGENT_CONTRACT.redemption.idempotencyHeader}"\`, \`idempotencyRequired: true\`, invite expiry, and \`nextAction: "redeem_and_save_profile"\`.`,
    '- The `/api/...` endpoint is a deployment-base-relative suffix: append it to this deployment’s canonical HTTPS base so a base-path prefix is preserved. Do not resolve it as an origin-root URL, and never derive the base from an untrusted Host, forwarded-host header, or request origin.',
    '- Do not log or persist the invite URL. Send it only to the intended collaborator.',
    '',
    '### 3. Redeem an invite and recover safely',
    '',
    `POST ${redeemUrl}`,
    '',
    '```bash',
    "INVITE_URL='https://nabu.example.test/invites/EXAMPLE_ONLY'",
    "IDEMPOTENCY_KEY='example-key-generated-with-at-least-128-bits-of-entropy'",
    `curl -sS -X POST ${redeemUrl} \\`,
    "  -H 'Content-Type: application/json' \\",
    '  -H "Idempotency-Key: ${IDEMPOTENCY_KEY}" \\',
    `  --data "{\\"inviteUrl\\":\\"\${INVITE_URL}\\"}"`,
    '```',
    '',
    '- The JSON field is exactly `inviteUrl`; do not substitute `invite`, `token`, or `inviteToken`.',
    '- Do not GET the invite URL as the redemption operation. A direct GET may return 404; redemption is the JSON POST above.',
    `- Version-${SHARED_SPACE_AGENT_CONTRACT.version} redemption requires a client-generated \`${SHARED_SPACE_AGENT_CONTRACT.redemption.idempotencyHeader}\` with at least 128 bits of entropy. Validate its length and allowed characters before sending it; never print or persist the key as ordinary text.`,
    `- A successful \`200\` response preserves every version-1 field and adds \`contractVersion: ${SHARED_SPACE_AGENT_CONTRACT.version}\`, deterministic non-secret \`profileId\`, \`nextAction: "save_credential_profile"\`, and exactly four relative, token-free \`links\`: \`tree\`, \`rootFolder\`, \`noteByPath\`, and \`search\`.`,
    `- The fixed link templates are \`${SHARED_SPACE_AGENT_CONTRACT.redemption.responseLinks.tree}\`, \`${SHARED_SPACE_AGENT_CONTRACT.redemption.responseLinks.rootFolder}\`, \`${SHARED_SPACE_AGENT_CONTRACT.redemption.responseLinks.noteByPath}\`, and \`${SHARED_SPACE_AGENT_CONTRACT.redemption.responseLinks.search}\`. Append each deployment-base-relative suffix to the canonical base; do not resolve it as an origin-root URL that drops a base-path prefix. Encode only the allowlisted variables; links contain no token or \`Authorization\` material.`,
    '- Keep the returned `accessToken` in memory only long enough to write the profile below, or put it in that approved profile. Never print it, commit it, place it in Markdown, or put it in a URL.',
    '- Use the token on normal vault APIs:',
    '  `Authorization: Bearer <accessToken>`',
    '- If a network failure leaves redemption status unknown, retry the exact same invite URL with the exact same `Idempotency-Key`. The same invite/key pair returns the identical token and metadata; a different key remains rejected. If both the invite and key are lost, ask the owner for a new invite.',
    `- Headerless redemption keeps version-1 one-shot behavior. A version-1 response without \`contractVersion\` is the v1 fallback signal for an older server: redeem once, persist securely, and do not assume retry safety.`,
    '- `410 SHARED_SPACE_INVITE_INVALID` covers malformed, expired, already redeemed, revoked, or unavailable invites. Treat a locally expired profile or a failed verification as unusable; never silently reuse it or request a broader token.',
    '- Each additional collaborator needs a newly generated one-time invite.',
    '',
    '### 4. Persist one scoped credential profile',
    '',
    'The profile is runtime-local persistence for one deployment and one shared space. It contains only the scoped collaborator token; owner passwords remain in an OS secret store.',
    '',
    '```text',
    ...SHARED_SPACE_AGENT_CONTRACT.profile.example,
    '```',
    '',
    '- Parse exactly this newline-delimited allowlist. Reject duplicate or unknown keys, malformed encoding, multiline values, and missing required fields; never shell-source the file.',
    `- Choose the profile directory in this order: explicit \`NABU_CREDENTIALS_DIR\`; Codex \`${SHARED_SPACE_AGENT_CONTRACT.profile.codexPath}\`; then Hermes \`${SHARED_SPACE_AGENT_CONTRACT.profile.hermesPath}\`.`,
    '- `<deployment-id>` is a deterministic filename-safe encoding of the exact canonical HTTPS API base, including a non-default port and base-path prefix. The profile filename comes only from the validated server-issued shared-space/profile ID.',
    '- On POSIX, directories are `0700` and profiles `0600`. On Windows, the profile has a current-user-only DACL. Reject symlinks/reparse points, wrong owners, and over-permissive destinations before reading the token.',
    '- Write atomically: create an exclusive temporary file in the same directory, flush it, atomically rename it into place, then verify ownership and permissions. Do not leave temporary copies or print diagnostics containing the token.',
    '',
    '### 5. Discover and verify at the beginning of a chat',
    '',
    '- Normalize the requested deployment to the exact canonical HTTPS API base URL before scanning profiles. Scan only that deployment directory. If no deployment is named and more than one canonical base exists, ask the user instead of guessing.',
    '- Reject malformed, symlinked, wrong-owner, over-permissive, or locally expired profiles. Filter candidate roots using normalized segment-aware containment (`projects/example` does not contain `projects/example-private`), then select the greatest segment depth. equal-depth duplicates are an ambiguity and must stop discovery rather than silently choosing.',
    `- Import the legacy Hermes single-file profile at \`${SHARED_SPACE_AGENT_CONTRACT.profile.legacyHermesPath}\` only when no structured profile exists for that deployment; validate it with the same allowlist and migrate it to the structured path atomically before use.`,
    '- verify the selected bearer token against the scoped tree or another in-scope read before any requested note operation. A 401/expired/revoked response means the profile is unusable; request a new invite only after reporting that verification failed.',
    '',
    '### 6. Issue a read-only URL token',
    '',
    `POST ${readLinkUrl}`,
    '',
    '```json',
    '{ "durationDays": 14 }',
    '```',
    '',
    '- This is owner-only. `durationDays` must be between 1 and 183 days; the default is 7 days and the effective expiry cannot outlive the shared space.',
    '- The response returns `shareUrl`, `sharedSpaceId`, `rootPath`, `permission: "read"`, `durationDays`, and `expiresAt`. The opaque token is only in `shareUrl`.',
    '- There is exactly one active read-only URL token per shared space. Issuing another token immediately invalidates the previous one.',
    '- `DELETE /api/shared-spaces/:sharedSpaceId/read-link` revokes the current URL token without revoking the shared space. Repeating the DELETE is safe.',
    '- Treat `shareUrl` as a secret capability. Never print it, commit it, or save it in an ordinary workspace file.',
    '- A human can open the returned URL directly, for example `https://nabu.example.com/?path=projects%2Fcanner&token=OPAQUE_TOKEN`. The browser shows the shared subtree in read-only mode and keeps the token while navigating within that subtree.',
    '- Agents can use the same token on read APIs as a query parameter, for example `GET /api/vault/tree?token=OPAQUE_TOKEN` or `GET /api/vault/notes/by-path?path=projects%2Fcanner%2Freadme.md&token=OPAQUE_TOKEN`.',
    '- Public reads cannot access parent, sibling, or outside paths. Such links return a generic `Shared space unavailable` response; local in-scope assets use `/api/vault/assets?path=<vault-relative-file>&token=OPAQUE_TOKEN`.',
    '- Do not use a read-only URL token on write endpoints. It has no write permission and must never be upgraded by the agent.',
    '',
    '### Shared-space management',
    '',
    '- `GET /api/shared-spaces/` lists spaces owned by the authenticated owner.',
    '- `GET /api/shared-spaces/:sharedSpaceId` inspects an owned space.',
    '- `POST /api/shared-spaces/:sharedSpaceId/revoke` revokes the space immediately; existing tokens fail synchronously.',
    '- `POST /api/shared-spaces/:sharedSpaceId/invites` creates another one-time invite for an active owned space.',
    '- `POST /api/shared-spaces/:sharedSpaceId/extend` requires explicit confirmation and may not exceed the 183-day maximum.',
    '',
    'Extension body:',
    '',
    '```json',
    '{ "confirmed": true, "durationDays": 7 }',
    '```',
    '',
    'Owner-only management operations must use the owner password session or the password-derived owner bearer credential. Shared collaborators cannot create broader credentials, extend leases, or revoke spaces.',
    '',
    '## Error contract',
    '',
    '- `400`: invalid path, invalid request body, invalid duration, or invalid permissions. Fix the request; do not retry unchanged.',
    '- `401`: missing, expired, or revoked authentication. Re-authenticate as owner or use a valid shared token.',
    '- `403`: authenticated principal lacks permission for the operation or path.',
    '- `404`: note/folder not found or intentionally hidden because it is outside the shared scope.',
    '- `409`: create conflict, move destination exists, folder is not empty, raw source conflict, or stale note revision.',
    '- `410 SHARED_SPACE_INVITE_INVALID`: invite is invalid, expired, redeemed, revoked, or its space is unavailable.',
    '- `428 WRITE_REVISION_REQUIRED`: re-read the note and retry with `If-Match` or `expectedRevision`.',
    '- When present, use structured `code`, `nextAction`, `readUrl`, and `currentRevision` fields to decide the next request.',
    '- Do not expose or repeat private paths from errors, search results, backlinks, neighborhoods, or graph responses.',
    '',
    '## MCP',
    '',
    `- Local command: ${bootstrap.mcp.localCommand}.`,
    `- Direct-vault environment: ${bootstrap.mcp.directEnvironment.join(', ')}.`,
    `- Deployed-service environment: ${bootstrap.mcp.remoteEnvironment.join(', ')}.`,
    `- Transport: ${bootstrap.mcp.transport}.`,
    `- Native remote MCP endpoint: ${bootstrap.mcp.nativeRemoteEndpoint}; do not assume it is the same as local stdio.`,
    '- Use the same Nabu password for remote MCP, keep it outside the repository, and use HTTPS for non-loopback services.',
    '- The MCP and HTTP layers use the same domain service and authorization rules.',
    '',
    '## Deployment requirements',
    '',
    '- A deployment may be operated by anyone, so agents must use the deployment-specific `/agents.md` rather than assuming a hosted Nabu version.',
    '- Shared-space leases, invite hashes, and access-token hashes must live in durable server-side metadata, not Markdown files or ephemeral per-request memory.',
    '- If the deployment runs multiple instances, all instances must share the same durable metadata store and vault; otherwise one-time redemption and revocation consistency cannot be guaranteed.',
    '- Never store raw invite or access-token secrets. Use cryptographically secure randomness, hashed persistence, atomic redemption, and server-time expiry checks.',
    '',
    '## Safety checklist',
    '',
    '- For sharing: preview -> show complete scope -> obtain explicit confirmation -> confirm -> distribute one-time invite.',
    '- For redemption: POST the exact `inviteUrl` payload once -> capture the token securely -> use bearer auth -> never log the secret.',
    '- For writes: read -> edit/merge -> send revision precondition -> on 409/428 re-read and retry safely -> verify by canonical path.',
    '- For private data: authorize before reading or mutating every endpoint and filter all derived results to the caller scope.',
    '',
  ])
}
