import { getAgentBootstrapContract } from '../lib/agent/bootstrap'

function lines(parts: Array<string | null | undefined | false>): string {
  return parts.filter(Boolean).join('\n')
}

function withBaseUrl(baseUrl: string, routePath: string): string {
  return `${baseUrl.replace(/\/$/, '')}${routePath}`
}

export function renderAgentsMarkdown(baseUrl = 'http://localhost:3000'): string {
  const bootstrap = getAgentBootstrapContract()
  const loginUrl = withBaseUrl(baseUrl, '/api/auth/login')
  const proposalUrl = withBaseUrl(baseUrl, '/api/shared-spaces/proposals')
  const sharedSpacesUrl = withBaseUrl(baseUrl, '/api/shared-spaces/')
  const notesUrl = withBaseUrl(baseUrl, '/api/vault/notes')
  const notesByPathUrl = withBaseUrl(baseUrl, '/api/vault/notes/by-path')

  return lines([
    '# /agents.md',
    '',
    'Complete agent contract for this Nabu instance.',
    '',
    'This document is public and returns raw Markdown. Read this route before touching the browser UI. Protected API operations still require owner authentication or a scoped shared-space token.',
    '',
    '## Operating rules',
    '',
    '- Use the HTTP API for normal note operations. Use MCP when the deployment or agent integration requires it.',
    '- Do not use browser automation or browser-use for normal note operations. Use the browser only for human navigation or explicit UI testing.',
    '- Use HTTPS for non-loopback deployments.',
    '- Check the HTTP status and JSON body on every request; do not treat an HTTP error as a successful operation.',
    '- Never log, persist, or commit passwords, session cookies, invite URLs, access tokens, or agent tokens.',
    '- Use vault-relative paths only. Never send absolute paths, traversal paths, or paths outside the vault.',
    '',
    '## Base URL and contract discovery',
    '',
    '- Set `NABU_URL` to this deployment base URL, without a trailing slash.',
    `- This deployment base URL is ${baseUrl.replace(/\/$/, '')}.`,
    '- Fetch `${NABU_URL}/agents.md` again whenever the deployment or API version is uncertain.',
    '- The contract is available without authentication so a new agent can discover the correct workflow before logging in or redeeming an invite.',
    '',
    '## Authentication',
    '',
    '- Existing password sessions and `NABU_AGENT_TOKEN` owner authentication remain supported. This shared-space flow does not replace them.',
    '- Owner login uses `POST /api/auth/login` with `Content-Type: application/x-www-form-urlencoded` and fields `password` and `redirect`.',
    `- A successful login sets the ${bootstrap.auth.cookieName} session cookie. Persist it in a cookie jar and reuse it for owner requests.`,
    '- Shared collaborators use `Authorization: Bearer <scoped-access-token>`; they do not use the owner password.',
    '- A shared token is scoped to exactly one shared space, its permissions, and its lease expiry. It cannot be broadened or extended by the collaborator.',
    '',
    '### Owner login example',
    '',
    '```bash',
    "curl -i -c /tmp/nabu-cookies.txt \\",
    "  -H 'Content-Type: application/x-www-form-urlencoded' \\",
    "  --data 'password=YOUR_PASSWORD&redirect=%2Fagents.md' \\",
    `  ${loginUrl}`,
    '```',
    '',
    '## Note identity and read surfaces',
    '',
    `- Canonical note identity is ${bootstrap.identity.canonical} (the vault-relative relPath).`,
    `- Prefer deterministic reads through ${bootstrap.identity.deterministicRead}<path>.`,
    `- Slug lookup through ${bootstrap.identity.convenienceRead} is convenience-only and may collide.`,
    '- URL-encode query parameters such as `path`, `q`, and `tag`.',
    '',
    '- `GET /api/vault/`',
    '- `GET /api/vault/index/stats`',
    '- `GET /api/vault/tree`',
    '- `GET /api/vault/folders?path=`',
    '- `GET /api/vault/notes/$slug`',
    '- `GET /api/vault/notes/by-path?path=`',
    '- `GET /api/vault/notes/neighborhood?path=`',
    '- `GET /api/vault/search?q=&path=&tag=&limit=&offset=`',
    '',
    '## Note writes',
    '',
    '- `POST /api/vault/folders`',
    '- `DELETE /api/vault/folders?path=`',
    '- `POST /api/vault/notes`',
    '- `PUT /api/vault/notes/by-path`',
    '- `PATCH /api/vault/notes/by-path`',
    '- `DELETE /api/vault/notes/by-path?path=` (single note only)',
    '',
    '- Use `rawMarkdown`, not top-level `body` or `content`. Send note text as `rawMarkdown` or a structured `document`, never both.',
    '- Folder delete is empty-only and non-recursive.',
    '- When writing notes, prefer canonical frontmatter metadata through structured documents. Supported metadata includes `title`, `summary`, `tags`, `authors`, `source`, and `references`.',
    '- Use deterministic by-path reads after every mutation. Read the note again by canonical path and verify the content and metadata.',
    '- Move notes with `{ "path": "from.md", "toPath": "to.md" }`. Moves do not rewrite wiki-links or Markdown links.',
    '- Successful mutations rebuild the in-memory index immediately.',
    '',
    '### Revision-aware writes',
    '',
    '- Every note read returns `note.revision` and an `ETag` such as `"revision-42"`.',
    '- Shared-token updates and moves must send `If-Match: "<revision>"` or `expectedRevision` in the request body.',
    '- Existing owner agents may continue legacy writes without a revision during migration. Those responses include `migration.code = WRITE_REVISION_MIGRATION_REQUIRED`; migrate that agent to revision-aware writes.',
    '- On `428 WRITE_REVISION_REQUIRED`, GET the supplied `readUrl`, merge the intended change, and retry with the returned revision.',
    '- On `409 STALE_NOTE_REVISION`, GET `readUrl`, merge against `currentRevision`, and retry. Never silently overwrite a newer note.',
    '- Human source saves may send `expectedRawContentHash`; a `409` then means the raw file changed since it was read. `expectedContentHash` remains the parsed-note agent contract.',
    '',
    '### Create and update examples',
    '',
    '```bash',
    `curl -sS -b /tmp/nabu-cookies.txt -X POST ${notesUrl} \\`,
    "  -H 'Content-Type: application/json' \\",
    "  --data '{\"path\":\"projects/example/notes/example.md\",\"rawMarkdown\":\"# Example\"}'",
    '',
    `curl -sS -b /tmp/nabu-cookies.txt ${notesByPathUrl}?path=projects%2Fexample%2Fnotes%2Fexample.md`,
    '',
    `curl -sS -b /tmp/nabu-cookies.txt -X PUT ${notesByPathUrl} \\`,
    "  -H 'Content-Type: application/json' \\",
    "  -H 'If-Match: \"REVISION_FROM_READ\"' \\",
    "  --data '{\"path\":\"projects/example/notes/example.md\",\"rawMarkdown\":\"# Example\\n\\nUpdated\"}'",
    '```',
    '',
    '## Temporary shared spaces',
    '',
    'Shared spaces are temporary, live recursive knowledge boundaries. Existing descendants are accessible immediately, and files or folders created later under the shared root become accessible automatically until the lease expires or is revoked.',
    '',
    '- Do not share the vault root.',
    '- Shared roots are segment-aware; a path must match complete path segments, not merely a string prefix.',
    '- Shared spaces have no exclusion rules in v1; choose a narrower root instead.',
    '- A shared token cannot access parent paths, siblings, symlink targets, or metadata that reveals private paths.',
    '- Private linked notes are filtered from search, backlinks, neighborhoods, and graph results.',
    '- Lease duration defaults to 7 days, has a minimum of 1 day, and has a maximum of 30 days.',
    '- Access expires synchronously using server time. Cleanup may happen asynchronously.',
    '- Invite URLs are opaque one-time capabilities valid for one hour. They are not long-lived access tokens.',
    '',
    '### 1. Propose a scope (no sharing side effect)',
    '',
    `POST ${proposalUrl}`,
    '',
    '```json',
    '{',
    '  "path": "folder-to-share",',
    '  "durationDays": 14',
    '}',
    '```',
    '',
    '- Normalize and validate the vault-relative path first.',
    '- Reject empty/root paths, absolute paths, traversal, symlinks, and paths outside the vault.',
    '- Show the human the complete recursive `files` and `folders` lists, `fileCount`, `totalBytes`, `warnings`, proposal ID, and expiry before asking for confirmation.',
    '- The preview must clearly state: `Any files or folders added under this path later will also be part of the shared space.`',
    '- A proposal alone never shares anything.',
    '',
    '### 2. Confirm explicitly and create an invite',
    '',
    `POST ${sharedSpacesUrl}`,
    '',
    '```json',
    '{',
    '  "proposalId": "proposal_123",',
    '  "confirmed": true,',
    '  "durationDays": 14,',
    '  "permissions": ["read", "write"]',
    '}',
    '```',
    '',
    '- `confirmed: true` is mandatory. Never infer confirmation from a proposal request or from the original user wording.',
    '- `durationDays` must be between 1 and 30. Omitted duration uses the 7-day default where supported.',
    '- The proposal must be unexpired and owned by the authenticated owner.',
    '- The response includes a one-time `inviteUrl`, `inviteExpiresAt`, and `sharedSpaceExpiresAt`.',
    '- Do not log or persist the invite URL. Send it only to the intended collaborator.',
    '',
    '### 3. Redeem an invite exactly once',
    '',
    'The invite URL identifies the Nabu deployment that owns the shared space. Redeem it against that same deployment; the recipient does not need a Nabu instance.',
    '',
    '```text',
    'Invite URL: https://invite-host.example/invites/opaque-secret',
    'Redemption endpoint: https://invite-host.example/api/shared-spaces/invites/redeem',
    '```',
    '',
    '```bash',
    "INVITE_URL='https://invite-host.example/invites/opaque-secret' # use the exact inviteUrl returned by confirmation",
    'INVITE_API_ORIGIN="${INVITE_URL%%/invites/*}"',
    'curl -sS -X POST "$INVITE_API_ORIGIN/api/shared-spaces/invites/redeem" \\',
    "  -H 'Content-Type: application/json' \\",
    '  --data "{\\"inviteUrl\\":\\"$INVITE_URL\\"}"',
    '```',
    '',
    '- The JSON field is exactly `inviteUrl`; do not substitute `invite`, `token`, or `inviteToken`.',
    '- Do not GET the invite URL as the redemption operation. A direct GET may return 404; redemption is the JSON POST above.',
    '- Send redemption and subsequent shared-vault requests to the invite URL origin, not to an unrelated Nabu deployment.',
    '- A successful `200` response returns `sharedSpaceId`, `rootPath`, `permissions`, `sharedSpaceExpiresAt`, `accessToken`, and `accessTokenExpiresAt`.',
    '- Keep the returned access token in memory or an approved secret store only. Never print it, commit it, or place it in Markdown.',
    '- Use the token on normal vault APIs:',
    '  `Authorization: Bearer <accessToken>`',
    '- `410 SHARED_SPACE_INVITE_INVALID` means the invite is malformed, expired, already redeemed, or its space is expired/revoked. Do not retry alternate field names or blindly retry the same invite.',
    '- If a network failure leaves redemption status unknown, do not assume a retry is safe. Ask the owner to generate another invite if the token was not received.',
    '- Each additional collaborator needs a newly generated one-time invite.',
    '',
    '### Shared-space management',
    '',
    '- `GET /api/shared-spaces/` lists spaces owned by the authenticated owner.',
    '- `GET /api/shared-spaces/:sharedSpaceId` inspects an owned space.',
    '- `POST /api/shared-spaces/:sharedSpaceId/revoke` revokes the space immediately; existing tokens fail synchronously.',
    '- `POST /api/shared-spaces/:sharedSpaceId/invites` creates another one-time invite for an active owned space.',
    '- `POST /api/shared-spaces/:sharedSpaceId/extend` requires explicit confirmation and may not exceed the 30-day maximum.',
    '',
    'Extension body:',
    '',
    '```json',
    '{ "confirmed": true, "durationDays": 7 }',
    '```',
    '',
    'Owner-only management operations must use the owner password session or configured owner agent token. Shared collaborators cannot create broader tokens, extend leases, or revoke spaces.',
    '',
    '## Error contract',
    '',
    '- `400`: invalid path, invalid request body, invalid duration, or invalid permissions. Fix the request; do not retry unchanged.',
    '- `401`: missing, expired, or revoked authentication. Re-authenticate as owner or use a valid shared token.',
    '- `403`: authenticated principal lacks permission for the operation or path.',
    '- `404`: note/folder not found or intentionally hidden because it is outside the shared scope.',
    '- `409`: create conflict, move destination exists, folder is not empty, raw source conflict, or stale note revision.',
    '- `410 SHARED_SPACE_INVITE_INVALID`: invite is invalid, expired, redeemed, revoked, or its space is unavailable.',
    '- `428 WRITE_REVISION_REQUIRED`: re-read the note and retry with `If-Match` or `expectedRevision`.',
    '- When present, use structured `code`, `nextAction`, `readUrl`, and `currentRevision` fields to decide the next request.',
    '- Do not expose or repeat private paths from errors, search results, backlinks, neighborhoods, or graph responses.',
    '',
    '## MCP',
    '',
    `- Local command: ${bootstrap.mcp.localCommand}.`,
    `- Direct-vault environment: ${bootstrap.mcp.directEnvironment.join(', ')}.`,
    `- Deployed-service environment: ${bootstrap.mcp.remoteEnvironment.join(', ')}.`,
    `- Transport: ${bootstrap.mcp.transport}.`,
    `- Native remote MCP endpoint: ${bootstrap.mcp.nativeRemoteEndpoint}; do not assume it is the same as local stdio.`,
    '- The MCP and HTTP layers use the same domain service and authorization rules.',
    '',
    '## Deployment requirements',
    '',
    '- A deployment may be operated by anyone, so agents must use the deployment-specific `/agents.md` rather than assuming a hosted Nabu version.',
    '- Shared-space leases, invite hashes, and access-token hashes must live in durable server-side metadata, not Markdown files or ephemeral per-request memory.',
    '- If the deployment runs multiple instances, all instances must share the same durable metadata store and vault; otherwise one-time redemption and revocation consistency cannot be guaranteed.',
    '- Never store raw invite or access-token secrets. Use cryptographically secure randomness, hashed persistence, atomic redemption, and server-time expiry checks.',
    '',
    '## Safety checklist',
    '',
    '- For sharing: preview -> show complete scope -> obtain explicit confirmation -> confirm -> distribute one-time invite.',
    '- For redemption: POST the exact `inviteUrl` payload once -> capture the token securely -> use bearer auth -> never log the secret.',
    '- For writes: read -> edit/merge -> send revision precondition -> on 409/428 re-read and retry safely -> verify by canonical path.',
    '- For private data: authorize before reading or mutating every endpoint and filter all derived results to the caller scope.',
    '',
  ])
}
