/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVaultIndexRouteImport } from './routes/api/vault/index'
import { Route as ApiVaultTreeRouteImport } from './routes/api/vault/tree'
import { Route as ApiVaultFoldersRouteImport } from './routes/api/vault/folders'
import { Route as ApiVaultNotesSlugRouteImport } from './routes/api/vault/notes/$slug'
import { Route as ApiVaultIndexStatsRouteImport } from './routes/api/vault/index/stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultIndexRoute = ApiVaultIndexRouteImport.update({
  id: '/api/vault/',
  path: '/api/vault/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultTreeRoute = ApiVaultTreeRouteImport.update({
  id: '/api/vault/tree',
  path: '/api/vault/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultFoldersRoute = ApiVaultFoldersRouteImport.update({
  id: '/api/vault/folders',
  path: '/api/vault/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultNotesSlugRoute = ApiVaultNotesSlugRouteImport.update({
  id: '/api/vault/notes/$slug',
  path: '/api/vault/notes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultIndexStatsRoute = ApiVaultIndexStatsRouteImport.update({
  id: '/api/vault/index/stats',
  path: '/api/vault/index/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/vault/folders': typeof ApiVaultFoldersRoute
  '/api/vault/tree': typeof ApiVaultTreeRoute
  '/api/vault/': typeof ApiVaultIndexRoute
  '/api/vault/index/stats': typeof ApiVaultIndexStatsRoute
  '/api/vault/notes/$slug': typeof ApiVaultNotesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/vault/folders': typeof ApiVaultFoldersRoute
  '/api/vault/tree': typeof ApiVaultTreeRoute
  '/api/vault': typeof ApiVaultIndexRoute
  '/api/vault/index/stats': typeof ApiVaultIndexStatsRoute
  '/api/vault/notes/$slug': typeof ApiVaultNotesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/vault/folders': typeof ApiVaultFoldersRoute
  '/api/vault/tree': typeof ApiVaultTreeRoute
  '/api/vault/': typeof ApiVaultIndexRoute
  '/api/vault/index/stats': typeof ApiVaultIndexStatsRoute
  '/api/vault/notes/$slug': typeof ApiVaultNotesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/vault/folders'
    | '/api/vault/tree'
    | '/api/vault/'
    | '/api/vault/index/stats'
    | '/api/vault/notes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/vault/folders'
    | '/api/vault/tree'
    | '/api/vault'
    | '/api/vault/index/stats'
    | '/api/vault/notes/$slug'
  id:
    | '__root__'
    | '/'
    | '/api/vault/folders'
    | '/api/vault/tree'
    | '/api/vault/'
    | '/api/vault/index/stats'
    | '/api/vault/notes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiVaultFoldersRoute: typeof ApiVaultFoldersRoute
  ApiVaultTreeRoute: typeof ApiVaultTreeRoute
  ApiVaultIndexRoute: typeof ApiVaultIndexRoute
  ApiVaultIndexStatsRoute: typeof ApiVaultIndexStatsRoute
  ApiVaultNotesSlugRoute: typeof ApiVaultNotesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault/': {
      id: '/api/vault/'
      path: '/api/vault'
      fullPath: '/api/vault/'
      preLoaderRoute: typeof ApiVaultIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault/tree': {
      id: '/api/vault/tree'
      path: '/api/vault/tree'
      fullPath: '/api/vault/tree'
      preLoaderRoute: typeof ApiVaultTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault/folders': {
      id: '/api/vault/folders'
      path: '/api/vault/folders'
      fullPath: '/api/vault/folders'
      preLoaderRoute: typeof ApiVaultFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault/notes/$slug': {
      id: '/api/vault/notes/$slug'
      path: '/api/vault/notes/$slug'
      fullPath: '/api/vault/notes/$slug'
      preLoaderRoute: typeof ApiVaultNotesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault/index/stats': {
      id: '/api/vault/index/stats'
      path: '/api/vault/index/stats'
      fullPath: '/api/vault/index/stats'
      preLoaderRoute: typeof ApiVaultIndexStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiVaultFoldersRoute: ApiVaultFoldersRoute,
  ApiVaultTreeRoute: ApiVaultTreeRoute,
  ApiVaultIndexRoute: ApiVaultIndexRoute,
  ApiVaultIndexStatsRoute: ApiVaultIndexStatsRoute,
  ApiVaultNotesSlugRoute: ApiVaultNotesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
