/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgentsDotmdRouteImport } from './routes/agents[.]md'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVaultIndexRouteImport } from './routes/api/vault/index'
import { Route as ApiVaultTreeRouteImport } from './routes/api/vault/tree'
import { Route as ApiVaultSearchRouteImport } from './routes/api/vault/search'
import { Route as ApiVaultFoldersRouteImport } from './routes/api/vault/folders'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiVaultNotesByPathRouteImport } from './routes/api/vault/notes/by-path'
import { Route as ApiVaultNotesSlugRouteImport } from './routes/api/vault/notes/$slug'
import { Route as ApiVaultIndexStatsRouteImport } from './routes/api/vault/index/stats'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsDotmdRoute = AgentsDotmdRouteImport.update({
  id: '/agents.md',
  path: '/agents.md',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultIndexRoute = ApiVaultIndexRouteImport.update({
  id: '/api/vault/',
  path: '/api/vault/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultTreeRoute = ApiVaultTreeRouteImport.update({
  id: '/api/vault/tree',
  path: '/api/vault/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultSearchRoute = ApiVaultSearchRouteImport.update({
  id: '/api/vault/search',
  path: '/api/vault/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultFoldersRoute = ApiVaultFoldersRouteImport.update({
  id: '/api/vault/folders',
  path: '/api/vault/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultNotesByPathRoute = ApiVaultNotesByPathRouteImport.update({
  id: '/api/vault/notes/by-path',
  path: '/api/vault/notes/by-path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultNotesSlugRoute = ApiVaultNotesSlugRouteImport.update({
  id: '/api/vault/notes/$slug',
  path: '/api/vault/notes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultIndexStatsRoute = ApiVaultIndexStatsRouteImport.update({
  id: '/api/vault/index/stats',
  path: '/api/vault/index/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents.md': typeof AgentsDotmdRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/vault/folders': typeof ApiVaultFoldersRoute
  '/api/vault/search': typeof ApiVaultSearchRoute
  '/api/vault/tree': typeof ApiVaultTreeRoute
  '/api/vault/': typeof ApiVaultIndexRoute
  '/api/vault/index/stats': typeof ApiVaultIndexStatsRoute
  '/api/vault/notes/$slug': typeof ApiVaultNotesSlugRoute
  '/api/vault/notes/by-path': typeof ApiVaultNotesByPathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents.md': typeof AgentsDotmdRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/vault/folders': typeof ApiVaultFoldersRoute
  '/api/vault/search': typeof ApiVaultSearchRoute
  '/api/vault/tree': typeof ApiVaultTreeRoute
  '/api/vault': typeof ApiVaultIndexRoute
  '/api/vault/index/stats': typeof ApiVaultIndexStatsRoute
  '/api/vault/notes/$slug': typeof ApiVaultNotesSlugRoute
  '/api/vault/notes/by-path': typeof ApiVaultNotesByPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents.md': typeof AgentsDotmdRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/vault/folders': typeof ApiVaultFoldersRoute
  '/api/vault/search': typeof ApiVaultSearchRoute
  '/api/vault/tree': typeof ApiVaultTreeRoute
  '/api/vault/': typeof ApiVaultIndexRoute
  '/api/vault/index/stats': typeof ApiVaultIndexStatsRoute
  '/api/vault/notes/$slug': typeof ApiVaultNotesSlugRoute
  '/api/vault/notes/by-path': typeof ApiVaultNotesByPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents.md'
    | '/login'
    | '/logout'
    | '/api/auth/login'
    | '/api/vault/folders'
    | '/api/vault/search'
    | '/api/vault/tree'
    | '/api/vault/'
    | '/api/vault/index/stats'
    | '/api/vault/notes/$slug'
    | '/api/vault/notes/by-path'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents.md'
    | '/login'
    | '/logout'
    | '/api/auth/login'
    | '/api/vault/folders'
    | '/api/vault/search'
    | '/api/vault/tree'
    | '/api/vault'
    | '/api/vault/index/stats'
    | '/api/vault/notes/$slug'
    | '/api/vault/notes/by-path'
  id:
    | '__root__'
    | '/'
    | '/agents.md'
    | '/login'
    | '/logout'
    | '/api/auth/login'
    | '/api/vault/folders'
    | '/api/vault/search'
    | '/api/vault/tree'
    | '/api/vault/'
    | '/api/vault/index/stats'
    | '/api/vault/notes/$slug'
    | '/api/vault/notes/by-path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsDotmdRoute: typeof AgentsDotmdRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiVaultFoldersRoute: typeof ApiVaultFoldersRoute
  ApiVaultSearchRoute: typeof ApiVaultSearchRoute
  ApiVaultTreeRoute: typeof ApiVaultTreeRoute
  ApiVaultIndexRoute: typeof ApiVaultIndexRoute
  ApiVaultIndexStatsRoute: typeof ApiVaultIndexStatsRoute
  ApiVaultNotesSlugRoute: typeof ApiVaultNotesSlugRoute
  ApiVaultNotesByPathRoute: typeof ApiVaultNotesByPathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents.md': {
      id: '/agents.md'
      path: '/agents.md'
      fullPath: '/agents.md'
      preLoaderRoute: typeof AgentsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault/': {
      id: '/api/vault/'
      path: '/api/vault'
      fullPath: '/api/vault/'
      preLoaderRoute: typeof ApiVaultIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault/tree': {
      id: '/api/vault/tree'
      path: '/api/vault/tree'
      fullPath: '/api/vault/tree'
      preLoaderRoute: typeof ApiVaultTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault/search': {
      id: '/api/vault/search'
      path: '/api/vault/search'
      fullPath: '/api/vault/search'
      preLoaderRoute: typeof ApiVaultSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault/folders': {
      id: '/api/vault/folders'
      path: '/api/vault/folders'
      fullPath: '/api/vault/folders'
      preLoaderRoute: typeof ApiVaultFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault/notes/by-path': {
      id: '/api/vault/notes/by-path'
      path: '/api/vault/notes/by-path'
      fullPath: '/api/vault/notes/by-path'
      preLoaderRoute: typeof ApiVaultNotesByPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault/notes/$slug': {
      id: '/api/vault/notes/$slug'
      path: '/api/vault/notes/$slug'
      fullPath: '/api/vault/notes/$slug'
      preLoaderRoute: typeof ApiVaultNotesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault/index/stats': {
      id: '/api/vault/index/stats'
      path: '/api/vault/index/stats'
      fullPath: '/api/vault/index/stats'
      preLoaderRoute: typeof ApiVaultIndexStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsDotmdRoute: AgentsDotmdRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiVaultFoldersRoute: ApiVaultFoldersRoute,
  ApiVaultSearchRoute: ApiVaultSearchRoute,
  ApiVaultTreeRoute: ApiVaultTreeRoute,
  ApiVaultIndexRoute: ApiVaultIndexRoute,
  ApiVaultIndexStatsRoute: ApiVaultIndexStatsRoute,
  ApiVaultNotesSlugRoute: ApiVaultNotesSlugRoute,
  ApiVaultNotesByPathRoute: ApiVaultNotesByPathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
